-- Alineación única de niveles creados antes de incorporar la tributación
-- oficial de los programas del Plan 4 SCT. Las asignaturas no incluidas en
-- los programas entregados se conservan sin cambios.

WITH "AsignaturasRevisadas"("nombre") AS (
  VALUES
    ('Fundamentos Neuroanatómicos y Funcionales del Sistema Nervioso'),
    ('Fundamentos Socioculturales de la Psicología'),
    ('Procesos Psicológicos I'),
    ('Taller de Habilidades Profesionales I'),
    ('Introducción a la Psicología'),
    ('Electivo de Comunicación'),
    ('Psicología de la Personalidad'),
    ('Psicología Social'),
    ('Psicología del Desarrollo I: Primera y Segunda Infancia'),
    ('Teorías Psicológicas I'),
    ('Evaluación Psicométrica'),
    ('Intervención Psicosocial con Grupos'),
    ('Introducción a la Investigación en Psicología'),
    ('Psicología del Desarrollo II: Adolescencia y Adultez'),
    ('Teorías Psicológicas II'),
    ('Evaluación Proyectiva'),
    ('Intervención Sociocomunitaria'),
    ('Metodología y Análisis de Datos Cuantitativos'),
    ('Psicología Organizacional'),
    ('Teorías Psicológicas III'),
    ('Electivo de Desarrollo Personal'),
    ('Psicodiagnóstico Infanto Juvenil'),
    ('Intervención en Organizaciones'),
    ('Metodología y Análisis de Datos Cualitativos'),
    ('Psicopatología y Psicofarmacología Infanto Juvenil'),
    ('Teorías Psicológicas IV'),
    ('Electivo de Responsabilidad Social'),
    ('Psicodiagnóstico Adulto'),
    ('Intervención Clínica Infanto Juvenil'),
    ('Proyecto de Tesis'),
    ('Psicología de la Educación'),
    ('Psicopatología y Psicofarmacología Adulto'),
    ('Electivo de Ética'),
    ('Desempeño Ético del Psicólogo'),
    ('Intervención Clínica Adulto'),
    ('Seminario de Tesis'),
    ('Intervención Psicoeducativa en Contextos Escolares'),
    ('Psicología Jurídica'),
    ('Psicología de la Salud'),
    ('Práctica Avanzada I'),
    ('Práctica Avanzada II'),
    ('Convivencia Escolar'),
    ('Entrevista por Competencias'),
    ('Técnicas Psicoterapéuticas Infantojuveniles'),
    ('Diseño de Programas Sociales'),
    ('Evaluación de Programas Sociales'),
    ('Diseño y Evaluación de Programas Sociales y Sanitarios en Psicología')
)
DELETE FROM "MapeoAsignaturaCompetencia" AS "m"
USING "Asignatura" AS "a", "AsignaturasRevisadas" AS "r"
WHERE "m"."asignaturaId" = "a"."id"
  AND "a"."nombre" = "r"."nombre";

WITH "Programa"("nombre", "linea") AS (
  VALUES
    ('Fundamentos Neuroanatómicos y Funcionales del Sistema Nervioso', 1),
    ('Fundamentos Neuroanatómicos y Funcionales del Sistema Nervioso', 3),
    ('Fundamentos Socioculturales de la Psicología', 1),
    ('Fundamentos Socioculturales de la Psicología', 3),
    ('Fundamentos Socioculturales de la Psicología', 4),
    ('Procesos Psicológicos I', 3),
    ('Taller de Habilidades Profesionales I', 2),
    ('Taller de Habilidades Profesionales I', 6),
    ('Introducción a la Psicología', 3),
    ('Introducción a la Psicología', 4),
    ('Psicología de la Personalidad', 1),
    ('Psicología de la Personalidad', 3),
    ('Psicología de la Personalidad', 4),
    ('Psicología de la Personalidad', 5),
    ('Psicología Social', 1),
    ('Psicología Social', 3),
    ('Psicología Social', 4),
    ('Psicología del Desarrollo I: Primera y Segunda Infancia', 1),
    ('Psicología del Desarrollo I: Primera y Segunda Infancia', 2),
    ('Psicología del Desarrollo I: Primera y Segunda Infancia', 3),
    ('Psicología del Desarrollo I: Primera y Segunda Infancia', 4),
    ('Teorías Psicológicas I', 1),
    ('Teorías Psicológicas I', 3),
    ('Teorías Psicológicas I', 4),
    ('Evaluación Psicométrica', 1),
    ('Evaluación Psicométrica', 3),
    ('Evaluación Psicométrica', 4),
    ('Intervención Psicosocial con Grupos', 1),
    ('Intervención Psicosocial con Grupos', 2),
    ('Intervención Psicosocial con Grupos', 3),
    ('Intervención Psicosocial con Grupos', 4),
    ('Intervención Psicosocial con Grupos', 5),
    ('Intervención Psicosocial con Grupos', 6),
    ('Introducción a la Investigación en Psicología', 1),
    ('Introducción a la Investigación en Psicología', 2),
    ('Introducción a la Investigación en Psicología', 3),
    ('Introducción a la Investigación en Psicología', 4),
    ('Introducción a la Investigación en Psicología', 5),
    ('Psicología del Desarrollo II: Adolescencia y Adultez', 1),
    ('Psicología del Desarrollo II: Adolescencia y Adultez', 3),
    ('Psicología del Desarrollo II: Adolescencia y Adultez', 4),
    ('Teorías Psicológicas II', 1),
    ('Teorías Psicológicas II', 2),
    ('Teorías Psicológicas II', 3),
    ('Teorías Psicológicas II', 4),
    ('Teorías Psicológicas II', 5),
    ('Evaluación Proyectiva', 3),
    ('Evaluación Proyectiva', 4),
    ('Intervención Sociocomunitaria', 5),
    ('Metodología y Análisis de Datos Cuantitativos', 2),
    ('Metodología y Análisis de Datos Cuantitativos', 4),
    ('Psicología Organizacional', 3),
    ('Psicología Organizacional', 4),
    ('Teorías Psicológicas III', 4),
    ('Teorías Psicológicas III', 6),
    ('Psicodiagnóstico Infanto Juvenil', 3),
    ('Psicodiagnóstico Infanto Juvenil', 6),
    ('Intervención en Organizaciones', 3),
    ('Intervención en Organizaciones', 4),
    ('Intervención en Organizaciones', 5),
    ('Intervención en Organizaciones', 6),
    ('Metodología y Análisis de Datos Cualitativos', 2),
    ('Metodología y Análisis de Datos Cualitativos', 5),
    ('Metodología y Análisis de Datos Cualitativos', 6),
    ('Psicopatología y Psicofarmacología Infanto Juvenil', 3),
    ('Psicopatología y Psicofarmacología Infanto Juvenil', 4),
    ('Teorías Psicológicas IV', 3),
    ('Teorías Psicológicas IV', 4),
    ('Teorías Psicológicas IV', 5),
    ('Psicodiagnóstico Adulto', 3),
    ('Psicodiagnóstico Adulto', 4),
    ('Psicodiagnóstico Adulto', 6),
    ('Intervención Clínica Infanto Juvenil', 3),
    ('Intervención Clínica Infanto Juvenil', 4),
    ('Intervención Clínica Infanto Juvenil', 5),
    ('Intervención Clínica Infanto Juvenil', 6),
    ('Proyecto de Tesis', 2),
    ('Proyecto de Tesis', 4),
    ('Psicología de la Educación', 1),
    ('Psicología de la Educación', 3),
    ('Psicología de la Educación', 6),
    ('Psicopatología y Psicofarmacología Adulto', 4),
    ('Psicopatología y Psicofarmacología Adulto', 6),
    ('Desempeño Ético del Psicólogo', 1),
    ('Desempeño Ético del Psicólogo', 2),
    ('Desempeño Ético del Psicólogo', 6),
    ('Intervención Clínica Adulto', 4),
    ('Seminario de Tesis', 1),
    ('Seminario de Tesis', 2),
    ('Seminario de Tesis', 3),
    ('Seminario de Tesis', 4),
    ('Seminario de Tesis', 5),
    ('Seminario de Tesis', 6),
    ('Intervención Psicoeducativa en Contextos Escolares', 4),
    ('Intervención Psicoeducativa en Contextos Escolares', 5),
    ('Intervención Psicoeducativa en Contextos Escolares', 6),
    ('Psicología Jurídica', 3),
    ('Psicología Jurídica', 4),
    ('Psicología de la Salud', 3),
    ('Psicología de la Salud', 4),
    ('Psicología de la Salud', 5),
    ('Práctica Avanzada I', 1),
    ('Práctica Avanzada I', 3),
    ('Práctica Avanzada I', 4),
    ('Práctica Avanzada I', 5),
    ('Práctica Avanzada II', 1),
    ('Práctica Avanzada II', 3),
    ('Práctica Avanzada II', 4),
    ('Práctica Avanzada II', 5),
    ('Práctica Avanzada II', 6),
    ('Convivencia Escolar', 1),
    ('Convivencia Escolar', 4),
    ('Convivencia Escolar', 5),
    ('Entrevista por Competencias', 1),
    ('Entrevista por Competencias', 3),
    ('Técnicas Psicoterapéuticas Infantojuveniles', 1),
    ('Técnicas Psicoterapéuticas Infantojuveniles', 3),
    ('Técnicas Psicoterapéuticas Infantojuveniles', 4),
    ('Técnicas Psicoterapéuticas Infantojuveniles', 5),
    ('Diseño de Programas Sociales', 2),
    ('Diseño de Programas Sociales', 3),
    ('Evaluación de Programas Sociales', 2),
    ('Evaluación de Programas Sociales', 3),
    ('Diseño y Evaluación de Programas Sociales y Sanitarios en Psicología', 2),
    ('Diseño y Evaluación de Programas Sociales y Sanitarios en Psicología', 3)
)
INSERT INTO "MapeoAsignaturaCompetencia" ("id", "tipo", "asignaturaId", "competenciaId")
SELECT
  'programa_' || substr(md5("a"."id" || ':' || "c"."id"), 1, 24),
  'DIRECTA'::"TipoMapeo",
  "a"."id",
  "c"."id"
FROM "Programa" AS "p"
JOIN "Asignatura" AS "a" ON "a"."nombre" = "p"."nombre"
JOIN "Competencia" AS "c"
  ON "c"."nivelId" = "a"."nivelId"
 AND split_part("c"."codigo", '.', 1) = "p"."linea"::text
ON CONFLICT ("asignaturaId", "competenciaId")
DO UPDATE SET "tipo" = EXCLUDED."tipo";
